pipeline:
  - step: LoadImageStep
    input: null
    output: initial_image
    parameters:
      book: "birdsEuropeIGoul"
      pages: [1, 2, 34]

  - step: FixOrientationStep
    input: initial_image
    output: oriented_image

  - step: GrayscaleStep
    input: oriented_image
    output: grayscale_image

  - step: WhiteBalanceStep
    input: oriented_image
    output: white_balanced_image
    parameters:
      strength: 1.0
      k: 3
      max_size: 256

  - step: ReduceYellowStep
    input: white_balanced_image
    output: reduced_yellow_image
    parameters:
      grayscale_image: white_balanced_image
      tolerance: 30
      color: [245, 235, 225]

preview:
  enabled: true
  images:
    - name: reduced_yellow_image
      title: "Output"
      enabled: true
    - name: oriented_image
      title: "Oriented Image"
      enabled: true
    - name: white_balanced_image
      title: "White Balanced Image"
      enabled: true

