pipeline:
  - step: LoadImageStep
    input: null
    output: initial_image
    parameters:
      book: "birdsEuropeIGoul"
      # pages: [1, 2, 34]
      pages: [43]

  - step: FixOrientationStep
    input: initial_image
    output: oriented_image

  - step: GrayscaleStep
    input: oriented_image
    output: grayscale_image

  - step: WhiteBalanceStep
    input: oriented_image
    output: white_balanced_image
    parameters:
      strength: 1.0
      k: 3
      max_size: 256
      correction_min: 0.8
      correction_max: 1.2

  - step: ReduceYellowStep
    input: white_balanced_image
    output: reduced_yellow_image
    parameters:
      grayscale_image: white_balanced_image
      tolerance: 30
      color: [245, 235, 225]

  - step: BilateralFilterStep
    input: reduced_yellow_image
    output: bilateral_filtered_image
    parameters:
      diameter: 9
      sigma_color: 75
      sigma_space: 75

  - step: MaskColorStep
    input: bilateral_filtered_image
    output: non_white_mask
    parameters:
      color: [255, 255, 255]

  - step: BrightnessContrastStep
    input: bilateral_filtered_image
    mask: non_white_mask
    output: bright_contrast_image
    parameters:
      brightness: -40
      contrast: 30

  - step: GrayscaleStep
    input: bright_contrast_image
    output: bright_contrast_grayscale_image

  - step: FindMinorContoursStep
    input: bright_contrast_grayscale_image
    output: minor_contours

preview:
  enabled: true
  images:
    - name: bright_contrast_image
      title: "Output"
      enabled: true
    - name: oriented_image
      title: "Oriented Image"
      enabled: true
    - name: white_balanced_image
      title: "White Balanced Image"
      enabled: true
    - name: non_white_mask
      title: "Non White Mask"
      enabled: false
    - name: minor_contours
      title: "Minor Contours Mask"
      enabled: true

