pipeline:
  - step: LoadImageStep
    output: initial_image
    input: null
    parameters:
      book: "birdsEuropeIGoul"
      pages: [1, 2, 31]
  - step: GrayscaleStep
    input: initial_image
    output: grayscale_image
  - step: ResizeStep
    input: grayscale_image
    output: resized_image
    parameters:
      height: 800