pipeline:
  - step: LoadImageStep
    input: null
    output: initial_image
    parameters:
      book: "birdsEuropeIGoul"
      pages: [1, 2, 34]

  - step: FixOrientationStep
    input: initial_image
    output: oriented_image

  - step: GrayscaleStep
    input: oriented_image
    output: grayscale_image

  - step: ResizeStep
    input: grayscale_image
    output: resized_image
    parameters:
      max: 800